# Generated by Django 2.0.5 on 2018-06-04 15:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(blank=True, max_length=50)),
                ('isOrganisation', models.BooleanField(default=False)),
                ('imagePath', models.ImageField(upload_to='static/images/avatars')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('icon', models.CharField(default='fa fa-gift', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='IntervalConstraint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startDate', models.DateTimeField()),
                ('endDate', models.DateTimeField()),
                ('available', models.BooleanField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Query',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('category', models.CharField(choices=[('WISSEN & DIENSTLEISTUNGEN', 'Wissen & Dienstleistungen'), ('BÜCHER, MUSIK & FILM', 'Bücher, Musik & Film'), ('SPIEL, SPORT & FREIZEIT', 'Spiel, Sport & Freizeit'), ('HAUSHALTSINVENTAR', 'Haushaltsinventar'), ('TRANSPORTMITTEL', 'Transportmittel'), ('BÜROARTIKEL', 'Büroartikel'), ('ELEKTRONIK & TECHNIK', 'Elektronik & Technik'), ('VERANSTALTUNGSEQUIPMENT', 'Veranstaltungsequipment'), ('RÄUMLICHKEITEN', 'Räumlichkeiten'), ('WERKZEUGE', 'Werkzeuge')], max_length=186)),
                ('startDate', models.DateTimeField()),
                ('endDate', models.DateTimeField()),
                ('ambit', models.IntegerField(choices=[(5, '5 km'), (10, '10 km'), (20, '20 km'), (30, '30 km')], default=5)),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('locationLat', models.FloatField()),
                ('locationLong', models.FloatField()),
                ('description', models.CharField(max_length=400)),
                ('costs', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('imagePath', models.ImageField(upload_to='static/images/offers')),
                ('deposit', models.CharField(blank=True, max_length=30, null=True)),
                ('type', models.CharField(choices=[('ZU VERSCHENKEN', 'Zu Verschenken'), ('ZU VERLEIHEN', 'Zu Verleihen'), ('ZUR MIETE', 'Zur Miete')], default='ZU VERSCHENKEN', max_length=30)),
                ('categoryId', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='Cith2.Category')),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Watchlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resourceId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Cith2.Resource')),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='intervalconstraint',
            name='resourceId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Cith2.Resource'),
        ),
    ]
