# Generated by Django 2.0.5 on 2018-06-06 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cith2', '0002_auto_20180606_2109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='imagePath',
            field=models.ImageField(default='static/images/avatars/avatar-1.jpg', upload_to='static/images/avatars'),
        ),
    ]
