# Generated by Django 2.0.4 on 2018-06-07 18:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Cith2', '0003_auto_20180606_2133'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='account',
            name='organisationName',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='query',
            name='category',
            field=models.CharField(choices=[('WISSEN & DIENSTLEISTUNGEN', 'Wissen & Dienstleistungen'), ('BÜCHER, MUSIK & FILM', 'Bücher, Musik & Film'), ('SPIEL, SPORT & FREIZEIT', 'Spiel, Sport & Freizeit'), ('HAUSHALTSINVENTAR', 'Haushaltsinventar'), ('TRANSPORTMITTEL', 'Transportmittel'), ('BÜROARTIKEL', 'Büroartikel'), ('ELEKTRONIK & TECHNIK', 'Elektronik & Technik'), ('VERANSTALTUNGSEQUIPMENT', 'Veranstaltungsequipment'), ('RÄUMLICHKEITEN', 'Räumlichkeiten'), ('WERKZEUGE', 'Werkzeuge')], max_length=50),
        ),
        migrations.AddField(
            model_name='account',
            name='plz',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='Cith2.Plz'),
        ),
    ]
