# Generated by Django 2.0.4 on 2018-06-07 19:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Cith2', '0004_auto_20180607_2009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='plz',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Cith2.Plz'),
        ),
    ]
