# Generated by Django 2.0.4 on 2018-06-07 23:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Cith2', '0006_auto_20180607_2152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='plz',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='Cith2.Plz'),
        ),
    ]
