# Generated by Django 2.0.6 on 2018-06-21 10:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Cith2', '0008_auto_20180610_1649'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intervalconstraint',
            name='resourceId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='constraints', to='Cith2.Resource'),
        ),
    ]
