# Generated by Django 2.0.5 on 2018-07-01 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cith2', '0009_auto_20180621_1236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='query',
            name='ambit',
            field=models.IntegerField(choices=[('5', '5'), ('10', '10'), ('20', '20'), ('30', '30')], default='5'),
        ),
    ]
