# Generated by Django 2.0.5 on 2018-07-01 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cith2', '0010_auto_20180701_2257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='query',
            name='ambit',
            field=models.IntegerField(choices=[(5, '5 km'), (10, '10 km'), (20, '20 km'), (30, '30 km')], default=5),
        ),
    ]
