# Generated by Django 2.0.6 on 2018-07-03 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cith2', '0011_auto_20180701_2325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='query',
            name='ambit',
            field=models.FloatField(choices=[(0.04500373929, '5 km'), (0.09000747858, '10 km'), (0.1800149572, '20 km'), (0.2700224358, '30 km')], default=5),
        ),
    ]
