# Generated by Django 2.0.6 on 2018-07-05 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cith2', '0012_auto_20180703_1125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='query',
            name='endDate',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='query',
            name='startDate',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
